Repository ComPWA/gluex-nstar, pull requests merged in 2024-07, with the labels that each got.

#46 DX: activate all Ruff linting rules
  .pre-commit-config.yaml
  docs/pgamma-state.ipynb
  pyproject.toml
Labels: 🖱️ DX

#45 DOC: shorten title in `README.md`
  README.md
Labels: 📝 Docs

#50 DX: remove redundant cell metadata from notebooks
  .pre-commit-config.yaml
  docs/pgamma-state.ipynb
Labels: 🔨 Maintenance, 🖱️ DX

#51 DOC: fix N* LaTeX rendering in `README.md`
  README.md
Labels: 🐛 Bug, 📝 Docs

#53 DX: define `doclive` Pixi job to skip notebook execution
  .pre-commit-config.yaml
  docs/conf.py
  pixi.toml
  pyproject.toml
Labels: 🖱️ DX

#13 DOC: formulate pure SymPy amplitude model
  .github/workflows/ci-docs.yml
  docs/index.md
  docs/symbolics.ipynb
Labels: 📝 Docs

#29 DOC: formulate AmpForm model for K⁺π⁰Λ
  docs/ampform/LambdaKpi0.ipynb
  docs/conf.py
  docs/index.md
  pixi.toml
Labels: 📝 Docs

#57 MAINT: remove version ranges and upgrade lock file
  pixi.lock
  pixi.toml
Labels: 🔨 Maintenance
