Repository ComPWA/gluex-nstar, pull requests merged in 2024-08, with the labels that each got.

#63 DX: activate Ruff formatting and linting in Jupyter Lab
  .pre-commit-config.yaml
  docs/ampform/LambdaKpi0.ipynb
  docs/ampform/etapi0p.ipynb
  docs/pgamma-state.ipynb
  pixi.lock
  pixi.toml
  pyproject.toml
Labels: 🖱️ DX

#64 MAINT: install packages from PyPI if possible
  pixi.lock
  pixi.toml
Labels: 🔨 Maintenance

#65 DX: merge `pixi.toml` into `pyproject.toml`
  pixi.lock
  pixi.toml
  pyproject.toml
Labels: 🖱️ DX

#69 DX: define `.envrc` for `direnv`
  .envrc
Labels: 🖱️ DX

#55 ENH: generate particle property table from database
  docs/ampform/LambdaKpi0.ipynb
  docs/conf.py
  pyproject.toml
Labels: ⚙️ Enhancement

#71 DX: clean GitHub Actions caches after closing PR
  .github/workflows/clean-caches.yml
Labels: 🖱️ DX

#56 FEAT: make 1D histograms interactive with sliders
  docs/ampform/LambdaKpi0.ipynb
  docs/ampform/etapi0p.ipynb
  pixi.lock
  pyproject.toml
Labels: ✨ Feature, 📝 Docs

#70 ENH: create 2D histograms with JAX
  docs/ampform/LambdaKpi0.ipynb
  pyproject.toml
Labels: ✨ Feature, 📝 Docs

#75 FEAT: adding coefficient and phase in sliders
  docs/ampform/LambdaKpi0.ipynb
  pyproject.toml
Labels: ✨ Feature

#77 ENH: webpage redesign
  .github/workflows/ci-docs.yml
  docs/_static/favicon.ico
  docs/branching-fraction.md
  docs/conf.py
  docs/eta-pi-p/automated.ipynb
  docs/eta-pi-p/index.md
  docs/eta-pi-p/manual.ipynb
  docs/eta-pi-p/pgamma-state.ipynb
  docs/eta-pi-p/reaction-model.md
  docs/index.md
  docs/lambda-k-pi/automated.ipynb
  docs/lambda-k-pi/index.md
  pyproject.toml
Labels: 📝 Docs

#79 MAINT: update `pixi.lock` and `.pre-commit-config.yml`
  .editorconfig
  .github/workflows/pr-linting.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .vscode/extensions.json
  .vscode/settings.json
  pixi.lock
  pyproject.toml
Labels: 🔨 Maintenance, 🖱️ DX

#80 DOC: render `ipympl` plots as exported figures
  .pre-commit-config.yaml
  docs/.gitignore
  docs/eta-pi-p/automated.ipynb
  docs/lambda-k-pi/automated.ipynb
Labels: 📝 Docs

#84 DX: update `.gitattributes` for github-linguist
  .gitattributes
Labels: 🖱️ DX

#85 DOC: update README.md
  README.md
Labels: 📝 Docs

#82 FEAT: add ampform-dpd notebook
  docs/lambda-k-pi/ampform-dpd.ipynb
  docs/lambda-k-pi/ampform.ipynb
  docs/lambda-k-pi/index.md
  pixi.lock
  pyproject.toml
Labels: ✨ Feature

#87 FEAT: implement amplitude visualization in manual notebook
  docs/eta-pi-p/index.md
  docs/eta-pi-p/manual.ipynb
  docs/lambda-k-pi/ampform-dpd.ipynb
  pyproject.toml
Labels: ✨ Feature, 📝 Docs

#92 ENH: add sliders and c-phi for etapip auto notebook
  docs/eta-pi-p/automated.ipynb
  pyproject.toml
Labels: ⚙️ Enhancement

#96 ENH: decrease `FloatSlider` step size
  docs/eta-pi-p/automated.ipynb
  docs/lambda-k-pi/ampform-dpd.ipynb
  docs/lambda-k-pi/ampform.ipynb
Labels: ⚙️ Enhancement

#95 ENH: add sliders in sympy etapipi notebook
  docs/eta-pi-p/automated.ipynb
  docs/eta-pi-p/manual.ipynb
Labels: ⚙️ Enhancement
